# Generated by Django 5.0.6 on 2024-06-20 05:28

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTypeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userTypeName', models.CharField(blank=True, max_length=200, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
