# Generated by Django 5.0.6 on 2024-08-02 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amcentrymodel',
            name='amcAbbreviation',
        ),
        migrations.RemoveField(
            model_name='aumentrymodel',
            name='aumAmcAbbreviation',
        ),
        migrations.RemoveField(
            model_name='aumyoygrowthentrymodel',
            name='aumYoyGrowthAmcAbbreviation',
        ),
        migrations.RemoveField(
            model_name='commissionentrymodel',
            name='commissionAmcAbbreviation',
        ),
        migrations.RemoveField(
            model_name='gstentrymodel',
            name='gstAmcAbbreviation',
        ),
        migrations.AddField(
            model_name='aumentrymodel',
            name='aumAmcName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aumAmcName', to='apis.amcentrymodel'),
        ),
        migrations.AddField(
            model_name='aumyoygrowthentrymodel',
            name='aumYoyGrowthAmcName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aumYoyGrowthAmcName', to='apis.amcentrymodel'),
        ),
        migrations.AddField(
            model_name='commissionentrymodel',
            name='commissionAmcName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissionAmcName', to='apis.amcentrymodel'),
        ),
        migrations.AddField(
            model_name='gstentrymodel',
            name='gstAmcName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gstAmcName', to='apis.amcentrymodel'),
        ),
    ]
