# Generated by Django 5.0.6 on 2024-07-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arnentrymodel',
            old_name='arnEvin',
            new_name='arnEuin',
        ),
    ]
