# Generated by Django 5.0.6 on 2024-07-16 10:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_rename_arnevin_arnentrymodel_arneuin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPreferenceModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AccountPreferenceName', models.CharField(blank=True, max_length=200, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountTypeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AccountTypeName', models.CharField(blank=True, max_length=200, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormTypeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('formTypeName', models.CharField(blank=True, max_length=200, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GstTypeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gstTypeName', models.CharField(blank=True, max_length=200, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IssueTypeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('issueTypeName', models.CharField(blank=True, max_length=200, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientbankmodel',
            name='clientPrimaryAccount',
        ),
        migrations.AddField(
            model_name='clientpowerofattorneymodel',
            name='clientPowerOfAttorneyUpload',
            field=models.FileField(blank=True, null=True, upload_to='clientPowerOfAttorneyUpload/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='clientbankmodel',
            name='clientAccountPreference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientAccountPreference', to='apis.accountpreferencemodel'),
        ),
        migrations.AlterField(
            model_name='clientbankmodel',
            name='clientBankAccountType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientBankAccountType', to='apis.accounttypemodel'),
        ),
        migrations.AlterField(
            model_name='formsmodel',
            name='formsType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formsType', to='apis.formtypemodel'),
        ),
        migrations.AlterField(
            model_name='amcentrymodel',
            name='amcGstType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amcGstType', to='apis.gsttypemodel'),
        ),
        migrations.AlterField(
            model_name='issuemodel',
            name='issueType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issueType', to='apis.issuetypemodel'),
        ),
        migrations.DeleteModel(
            name='DefaultAccountModel',
        ),
    ]
