# Generated by Django 5.0.6 on 2024-06-20 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_countrymodel_city_countrymodel_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryModel',
        ),
    ]
