# Generated by Django 5.0.6 on 2024-06-21 13:26

import django.core.validators
import django.db.models.deletion
import month.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_delete_countrymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmcEntryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amcAbbreviation', models.CharField(blank=True, max_length=200, null=True)),
                ('amcName', models.CharField(blank=True, max_length=200, null=True)),
                ('amcMobile', models.CharField(blank=True, max_length=200, null=True)),
                ('amcAddress', models.CharField(blank=True, max_length=500, null=True)),
                ('amcPinCode', models.IntegerField(blank=True, null=True)),
                ('amcEmail', models.EmailField(max_length=254, unique=True)),
                ('amcGstNo', models.CharField(blank=True, max_length=50, null=True)),
                ('amcGstType', models.CharField(blank=True, max_length=200, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArnEntryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arnNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('arnName', models.CharField(blank=True, max_length=200, null=True)),
                ('arnMobile', models.CharField(blank=True, max_length=200, null=True)),
                ('arnAddress', models.CharField(blank=True, max_length=500, null=True)),
                ('arnPinCode', models.IntegerField(blank=True, null=True)),
                ('arnEmail', models.EmailField(max_length=254, unique=True)),
                ('arnEvin', models.CharField(blank=True, max_length=200, null=True)),
                ('arnGstNo', models.CharField(blank=True, max_length=50, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('countryName', models.CharField(blank=True, max_length=200, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourierModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('courierClientName', models.CharField(blank=True, max_length=200, null=True)),
                ('courierClientAddress', models.CharField(blank=True, max_length=500, null=True)),
                ('courierMobileNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('courierEmail', models.EmailField(max_length=254, unique=True)),
                ('courierFile', models.FileField(blank=True, null=True, upload_to='courierFile/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndustryAumEntryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('industryName', models.CharField(blank=True, max_length=200, null=True)),
                ('industryAumDate', models.DateField(blank=True, null=True)),
                ('industryAumAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('industryAumSiplone', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IssueModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('issueName', models.CharField(blank=True, max_length=200, null=True)),
                ('issueType', models.CharField(blank=True, max_length=200, null=True)),
                ('issueDate', models.DateField(blank=True, null=True)),
                ('issueResolutionDate', models.DateField(blank=True, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stateName', models.CharField(blank=True, max_length=200, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AumEntryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aumInvoiceNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('aumAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aumMonth', month.models.MonthField(help_text='some help...', verbose_name='Month Value')),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('aumAmcAbbreviation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aumAmcAbbreviation', to='apis.amcentrymodel')),
                ('aumArnNumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aumArnNumber', to='apis.arnentrymodel')),
            ],
        ),
        migrations.CreateModel(
            name='AumYoyGrowthEntryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aumYoyGrowthAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aumYoyGrowthDate', models.DateField(blank=True, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('aumYoyGrowthAmcAbbreviation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aumYoyGrowthAmcAbbreviation', to='apis.amcentrymodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionEntryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('commissionAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commissionMonth', month.models.MonthField(help_text='some help...', verbose_name='Month Value')),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('commissionAmcAbbreviation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissionAmcAbbreviation', to='apis.amcentrymodel')),
                ('commissionArnNumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissionArnNumber', to='apis.arnentrymodel')),
            ],
        ),
        migrations.AddField(
            model_name='arnentrymodel',
            name='arnCountry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arnCountry', to='apis.countrymodel'),
        ),
        migrations.AddField(
            model_name='amcentrymodel',
            name='amcCountry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amcCountry', to='apis.countrymodel'),
        ),
        migrations.CreateModel(
            name='FormsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('formsType', models.CharField(blank=True, max_length=500, null=True)),
                ('formsFile', models.FileField(blank=True, null=True, upload_to='formsFile/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('formsAmcName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formsAmcName', to='apis.amcentrymodel')),
            ],
        ),
        migrations.CreateModel(
            name='GstEntryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gstInvoiceDate', models.DateField(blank=True, null=True)),
                ('gstInvoiceNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('gstTotalValue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gstTaxableValue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gstIGst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gstSGst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gstCGst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('gstAmcAbbreviation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gstAmcAbbreviation', to='apis.amcentrymodel')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marketingType', models.CharField(blank=True, max_length=500, null=True)),
                ('marketingFile', models.FileField(blank=True, null=True, upload_to='marketingFile/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('marketingAmcName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketingAmcName', to='apis.amcentrymodel')),
            ],
        ),
        migrations.CreateModel(
            name='NavModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('navFundName', models.CharField(blank=True, max_length=200, null=True)),
                ('nav', models.CharField(blank=True, max_length=200, null=True)),
                ('navDate', models.DateField(blank=True, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('navAmcName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navAmcName', to='apis.amcentrymodel')),
            ],
        ),
        migrations.CreateModel(
            name='StatementModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('statementDate', models.DateField(blank=True, null=True)),
                ('statementInvestorName', models.CharField(blank=True, max_length=200, null=True)),
                ('statementInvestorPanNo', models.CharField(blank=True, max_length=200, null=True)),
                ('statementInvestmentDate', models.DateField(blank=True, null=True)),
                ('statementFundName', models.CharField(blank=True, max_length=200, null=True)),
                ('statementCostOfInvestment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statementCurrentValue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statementSipDate', models.DateField(blank=True, null=True)),
                ('statementSipAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statementSwpAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statementSipBankName', models.CharField(blank=True, max_length=200, null=True)),
                ('statementSipBankAccountType', models.CharField(blank=True, max_length=200, null=True)),
                ('statementSipBankAccountLastFourDigit', models.IntegerField(blank=True, null=True)),
                ('statementPrimaryBankName', models.CharField(blank=True, max_length=200, null=True)),
                ('statementPrimaryBankAccountType', models.CharField(blank=True, max_length=200, null=True)),
                ('statementPrimaryBankAccountLastFourDigit', models.IntegerField(blank=True, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('statementAmcName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statementAmcName', to='apis.amcentrymodel')),
            ],
        ),
        migrations.AddField(
            model_name='arnentrymodel',
            name='arnState',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arnState', to='apis.statemodel'),
        ),
        migrations.AddField(
            model_name='amcentrymodel',
            name='amcState',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amcState', to='apis.statemodel'),
        ),
    ]
