# Generated by Django 5.0.6 on 2024-07-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_accountpreferencemodel_accounttypemodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountpreferencemodel',
            old_name='AccountPreferenceName',
            new_name='accountPreferenceName',
        ),
        migrations.RenameField(
            model_name='accounttypemodel',
            old_name='AccountTypeName',
            new_name='accountTypeName',
        ),
    ]
