# Generated by Django 5.0.6 on 2024-06-21 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_amcentrymodel_arnentrymodel_countrymodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statemodel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='apis.countrymodel'),
        ),
    ]
