# Generated by Django 5.0.6 on 2024-07-18 13:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_rename_accountpreferencename_accountpreferencemodel_accountpreferencename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couriermodel',
            name='courierFile',
        ),
        migrations.CreateModel(
            name='CourierFileModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('courierFile', models.FileField(blank=True, null=True, upload_to='courierFile/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier', to='apis.couriermodel')),
            ],
        ),
    ]
