# Generated by Django 5.0.6 on 2024-07-19 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_remove_couriermodel_courierfile_courierfilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='employeeFile',
            field=models.FileField(blank=True, null=True, upload_to='employeeFile/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'xls', 'xlsx', 'csv', 'txt'])]),
        ),
        migrations.AlterField(
            model_name='formsmodel',
            name='formsFile',
            field=models.FileField(blank=True, null=True, upload_to='formsFile/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'xls', 'xlsx', 'csv', 'txt'])]),
        ),
        migrations.AlterField(
            model_name='marketingmodel',
            name='marketingFile',
            field=models.FileField(blank=True, null=True, upload_to='marketingFile/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'xls', 'xlsx', 'csv', 'txt'])]),
        ),
    ]
