# Generated by Django 5.0.6 on 2024-06-24 11:09

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_statemodel_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymodel',
            name='countryName',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
