# Generated by Django 5.0.6 on 2024-06-25 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_countrymodel_countryname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amcentrymodel',
            name='amcEmail',
        ),
    ]
