# Generated by Django 5.0.6 on 2024-07-22 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_employeemodel_employeefile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relationship', models.CharField(blank=True, max_length=200, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='clientnomineemodel',
            name='clientNomineeDob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientnomineemodel',
            name='clientNomineeName',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='clientnomineemodel',
            name='clientNomineePanNo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='clientnomineemodel',
            name='clientNomineePercentageAllocation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='clientnomineemodel',
            name='clientNomineeRelation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientNomineeRelation', to='apis.relationshipmodel'),
        ),
        migrations.AlterField(
            model_name='clientnomineemodel',
            name='clientGuardianRelation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientGuardianRelation', to='apis.relationshipmodel'),
        ),
        migrations.DeleteModel(
            name='GuardianRelationshipModel',
        ),
    ]
