# Generated by Django 5.0.6 on 2024-07-22 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_relationshipmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientnomineemodel',
            old_name='clientGuardianName',
            new_name='clientNomineeGuardianName',
        ),
        migrations.RenameField(
            model_name='clientnomineemodel',
            old_name='clientGuardianPanNo',
            new_name='clientNomineeGuardianPanNo',
        ),
        migrations.RemoveField(
            model_name='clientnomineemodel',
            name='clientGuardianId',
        ),
        migrations.RemoveField(
            model_name='clientnomineemodel',
            name='clientGuardianRelation',
        ),
        migrations.AddField(
            model_name='clientnomineemodel',
            name='clientNomineeGuardianRelation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientNomineeGuardianRelation', to='apis.relationshipmodel'),
        ),
        migrations.AddField(
            model_name='clientnomineemodel',
            name='clientNomineeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientNomineeId', to='apis.clientmodel'),
        ),
        migrations.CreateModel(
            name='ClientGuardianModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clientGuardianName', models.CharField(blank=True, max_length=500, null=True)),
                ('clientGuardianPanNo', models.CharField(blank=True, max_length=500, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('clientGuardianId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientGuardianId', to='apis.clientmodel')),
                ('clientGuardianRelation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientGuardianRelation', to='apis.relationshipmodel')),
            ],
        ),
    ]
