# Generated by Django 5.0.6 on 2024-06-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_remove_statemodel_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankNameModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bankName', models.CharField(blank=True, max_length=200, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultAccountModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('defaultAccount', models.CharField(blank=True, max_length=200, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenderModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genderName', models.CharField(blank=True, max_length=200, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuardianRelationshipModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guardianRelationship', models.CharField(blank=True, max_length=200, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaritalStatusModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('maritalStatusName', models.CharField(blank=True, max_length=200, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoliticallyExposedPersonModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('politicallyExposedPersonName', models.CharField(blank=True, max_length=200, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='amcentrymodel',
            name='amcAbbreviation',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
