# Generated by Django 5.0.6 on 2024-06-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_banknamemodel_defaultaccountmodel_gendermodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amcentrymodel',
            name='amcAbbreviation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
