# Generated by Django 5.0.6 on 2024-07-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_clientpowerofattorneymodel_clientpowerofattorneyuploadname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='clientAadharNo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='clientEmail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='clientPanNo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
