# Generated by Django 5.0.6 on 2024-07-26 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_alter_clientmodel_clientaadharno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientpowerofattorneymodel',
            name='clientPowerOfAttorneyUpload',
        ),
        migrations.RemoveField(
            model_name='clientpowerofattorneymodel',
            name='clientPowerOfAttorneyUploadName',
        ),
        migrations.AddField(
            model_name='clientuploadfilemodel',
            name='clientPowerOfAttorneyUpload',
            field=models.FileField(blank=True, null=True, upload_to='clientPowerOfAttorneyUpload/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'pdf'])]),
        ),
    ]
