# Generated by Django 5.0.6 on 2024-06-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_alter_amcentrymodel_amcabbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amcentrymodel',
            name='amcAbbreviation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
