# Generated by Django 5.0.6 on 2024-07-26 07:18

import apis.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_remove_clientpowerofattorneymodel_clientpowerofattorneyupload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuploadfilemodel',
            name='clientAadharCard',
            field=models.FileField(blank=True, null=True, storage=apis.models.UniqueFileStorage(), upload_to='clientAadharCard/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='clientuploadfilemodel',
            name='clientBankAccountStatementOrPassbook',
            field=models.FileField(blank=True, null=True, storage=apis.models.UniqueFileStorage(), upload_to='clientBankAccountStatementOrPassbook/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='clientuploadfilemodel',
            name='clientCancelledChequeCopy',
            field=models.FileField(blank=True, null=True, storage=apis.models.UniqueFileStorage(), upload_to='clientCancelledChequeCopy/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='clientuploadfilemodel',
            name='clientChildrenBirthCertificate',
            field=models.FileField(blank=True, null=True, storage=apis.models.UniqueFileStorage(), upload_to='clientChildrenBirthCertificate/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='clientuploadfilemodel',
            name='clientDrivingLicense',
            field=models.FileField(blank=True, null=True, storage=apis.models.UniqueFileStorage(), upload_to='clientDrivingLicense/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='clientuploadfilemodel',
            name='clientForeignAddressProof',
            field=models.FileField(blank=True, null=True, storage=apis.models.UniqueFileStorage(), upload_to='clientForeignAddressProof/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='clientuploadfilemodel',
            name='clientForeignTaxIdentificationProof',
            field=models.FileField(blank=True, null=True, storage=apis.models.UniqueFileStorage(), upload_to='clientForeignTaxIdentificationProof/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='clientuploadfilemodel',
            name='clientPaasPortSizePhoto',
            field=models.FileField(blank=True, null=True, storage=apis.models.UniqueFileStorage(), upload_to='clientPaasPortSizePhoto/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='clientuploadfilemodel',
            name='clientPanCardPhoto',
            field=models.FileField(blank=True, null=True, storage=apis.models.UniqueFileStorage(), upload_to='clientPanCardPhoto/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='clientuploadfilemodel',
            name='clientPassportBackImage',
            field=models.FileField(blank=True, null=True, storage=apis.models.UniqueFileStorage(), upload_to='clientPassportBackImage/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='clientuploadfilemodel',
            name='clientPassportFrontImage',
            field=models.FileField(blank=True, null=True, storage=apis.models.UniqueFileStorage(), upload_to='clientPassportFrontImage/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='clientuploadfilemodel',
            name='clientPowerOfAttorneyUpload',
            field=models.FileField(blank=True, null=True, storage=apis.models.UniqueFileStorage(), upload_to='clientPowerOfAttorneyUpload/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='clientuploadfilemodel',
            name='clientVoterIDBackImage',
            field=models.FileField(blank=True, null=True, storage=apis.models.UniqueFileStorage(), upload_to='clientVoterIDBackImage/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='clientuploadfilemodel',
            name='clientVoterIDFrontImage',
            field=models.FileField(blank=True, null=True, storage=apis.models.UniqueFileStorage(), upload_to='clientVoterIDFrontImage/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'pdf'])]),
        ),
    ]
