# Generated by Django 5.0.6 on 2024-06-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_alter_amcentrymodel_amcabbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aumentrymodel',
            name='aumMonth',
            field=models.CharField(help_text='Format: YYYY-MM', max_length=7),
        ),
        migrations.AlterField(
            model_name='commissionentrymodel',
            name='commissionMonth',
            field=models.CharField(help_text='Format: YYYY-MM', max_length=7),
        ),
    ]
