# Generated by Django 5.0.6 on 2024-06-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_alter_aumentrymodel_aummonth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuemodel',
            name='issueDescription',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
