# Generated by Django 5.0.6 on 2024-06-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_issuemodel_issuedescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsmodel',
            name='formsDescription',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
