# Generated by Django 5.0.6 on 2024-06-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_formsmodel_formsdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingmodel',
            name='marketingDescription',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
