# Generated by Django 5.0.6 on 2024-06-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_marketingmodel_marketingdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taskTitle', models.CharField(blank=True, max_length=500, null=True)),
                ('taskClient', models.CharField(blank=True, max_length=500, null=True)),
                ('taskDate', models.DateField(blank=True, null=True)),
                ('taskTime', models.TimeField(blank=True, null=True)),
                ('taskLatitude', models.CharField(blank=True, max_length=500, null=True)),
                ('taskLongtitude', models.CharField(blank=True, max_length=500, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
