# Generated by Django 5.0.6 on 2024-06-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0017_taskmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='taskDescription',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
