# Generated by Django 5.0.6 on 2024-07-02 05:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0018_taskmodel_taskdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employeeName', models.CharField(blank=True, max_length=500, null=True)),
                ('employeeEmail', models.EmailField(max_length=254, unique=True)),
                ('employeePhone', models.CharField(blank=True, max_length=500, null=True)),
                ('employeePassword', models.CharField(blank=True, max_length=500, null=True)),
                ('employeeAddress', models.CharField(blank=True, max_length=2500, null=True)),
                ('employeeOtherDetail', models.CharField(blank=True, max_length=2500, null=True)),
                ('employeeFile', models.FileField(blank=True, null=True, upload_to='employeeFile/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('employeeUserType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employeeUserType', to='apis.usertypemodel')),
            ],
        ),
    ]
