# Generated by Django 5.0.6 on 2024-07-02 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0020_alter_employeemodel_employeeusertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='employeeUserType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employeeUserType', to='apis.usertypemodel'),
        ),
    ]
