# Generated by Django 5.0.6 on 2024-07-04 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0022_clientmodel_clientmedicalinsurancemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInsuranceModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clientInsurancePolicyNumber', models.CharField(blank=True, max_length=500, null=True)),
                ('clientInsurancePolicyName', models.CharField(blank=True, max_length=500, null=True)),
                ('clientInsurancePolicyCompanyName', models.CharField(blank=True, max_length=500, null=True)),
                ('clientInsurancePolicyTerm', models.CharField(blank=True, max_length=500, null=True)),
                ('clientInsurancePolicyMaturityAmount', models.CharField(blank=True, max_length=500, null=True)),
                ('clientInsurancePolicyPaymentPerInstallment', models.CharField(blank=True, max_length=500, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('clientInsuranceId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientInsuranceId', to='apis.clientmodel')),
            ],
        ),
    ]
