# Generated by Django 5.0.6 on 2024-07-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0023_clientinsurancemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientmodel',
            old_name='clientPassportLicenseNo',
            new_name='clientPassportNo',
        ),
        migrations.RemoveField(
            model_name='clientofficeaddressmodel',
            name='clientOfficeDistrict',
        ),
        migrations.RemoveField(
            model_name='clientoverseasaddressmodel',
            name='clientOverseasDistrict',
        ),
        migrations.AlterField(
            model_name='clientinsurancemodel',
            name='clientInsurancePolicyMaturityAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='clientmedicalinsurancemodel',
            name='clientMedicalInsurancePolicyMaturityAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='clientterminsurancemodel',
            name='clientTermInsurancePolicyMaturityAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
