# Generated by Django 5.0.6 on 2024-07-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0024_rename_clientpassportlicenseno_clientmodel_clientpassportno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbankmodel',
            name='clientBankPincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientbankmodel',
            name='clientPrimaryAccount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientofficeaddressmodel',
            name='clientOfficePincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientoverseasaddressmodel',
            name='clientOverseasPincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientpermanentaddressmodel',
            name='clientPermanentPincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientpresentaddressmodel',
            name='clientPresentPincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
