# Generated by Django 5.0.6 on 2024-07-09 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0025_alter_clientbankmodel_clientbankpincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbankmodel',
            name='clientPrimaryAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientPrimaryAccount', to='apis.defaultaccountmodel'),
        ),
    ]
