# Generated by Django 5.0.6 on 2024-07-11 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0026_alter_clientbankmodel_clientprimaryaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='taskClient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskClient', to='apis.clientmodel'),
        ),
    ]
